### ISSUE TITLE
Hazelcast Tomcat web session replication

### ISSUE THREAD

**Issue by RubavathiSrinivasan** [hazelcast/hazelcast-code-samples#67]
Hi, I try to test Hazelcast-filter based session replication, But it doesn't work, on failover it doesn't retain the cookie of other server.  
Do we need to set any tomcat configurations?

**Comment by RubavathiSrinivasan** [comment]
on server failover, it creates a new sessionid. 
We run three servers.
A http session is created with the HZ session id "HZ87EEE832D65749F5825F497D5D117914", on server1, 
If server1 goes down requests are redirected to server2 and a new HZ session is created "HZ740B5BB492CA48B7BFAF12224BDAF1D9"

Why is it creating a new session id? Is there anythig we need to do in config?

**Comment by gAmUssA** [comment]
@RubavathiSrinivasan please, share your https server (load balancer) details.
Thank you

**Comment by RubavathiSrinivasan** [comment]
@gAmUssA after added the cookie 'hazelcast.sessionId' and sticky session changes, it works fine now. But we need to maintain two session cookies, JSESSIONID and hazelcast.sessionId, is it possible to achieve session replication using JSESSIONID alone(especially on cluster failover) ? There are no clustered maps for originalsessionid as key and hazelcast.sessionId as value.

**Comment by mesutcelik** [comment]
`JSESSIONID` is controlled by web container and created if a new request comes into it. `hazelcast.sessionId` is used as clusterwide session id so that in case of failover new server figures out what session data is available for the new `JSESSIONID`.

To answer your question,`JSESSIONID` only is not sufficient for session replication.

This repository is not right place to discuss this. Can you please continue on [Google Groups](https://groups.google.com/forum/#!forum/hazelcast) if you still have questions?

Thanks for using Hazelcast!
